CREATE TABLE inquiries (
id INTEGER PRIMARY KEY AUTOINCREMENT,
topic TEXT NOT NULL,
email TEXT NOT NULL,
name TEXT NOT NULL,
order_number TEXT NOT NULL,
subject TEXT NOT NULL,
content TEXT NOT NULL,
created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL
) ;
