// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"time"
)

type Inquiry struct {
	ID          int64
	Topic       string
	Email       string
	Name        string
	OrderNumber string
	Subject     string
	Content     string
	CreatedAt   time.Time
}
