// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0

package database

import (
	"database/sql"
)

type Inquiry struct {
	ID          int64
	Topic       string
	Email       string
	Name        sql.NullString
	OrderNumber sql.NullString
	Subject     sql.NullString
	Content     string
	CreatedAt   sql.NullTime
}
